#!/usr/bin/env bash

# create the image
docker build -t siol-postgres-9-6 .

# start the container
docker run --name siol-postgres \
  -p 5432:5432 \
  -e POSTGRES_DB=sevenorless \
  -e POSTGRES_USER=sevenorless \
  -e POSTGRES_PASSWORD=winnie \
  -d siol-postgres-9-6

# connect to the container
psql \
  --host=127.0.0.1 \
  --port=5432 \
  --username sevenorless \
  --dbname=sevenorless

